apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  # labels of deployment resource
  labels:
    app: frontend
    tier: web
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      tier: web
      project: expense
  template:
    metadata:
      labels:
        app: frontend
        tier: web
        project: expense
    spec:
      containers:
      - name: nginx
        image: mahesh452/frontend:1.1.0
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector: # labels are used as selectors
    app: frontend
    tier: frontend
    project: expense
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 8080