apiVersion: apps/v1
kind: backendDeploy
metadata:
  name: backend
  namespace: expense
  # labels of deployment resource
  labels:
    app: backend
    tier: backend
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: backend
      project: expense
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        project: expense
    spec:
      containers:
      - name: nginx
        image: mahesh452/backend:1.1.0
---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense
spec:
  selector: # labels are used as selectors
    app: backend
    tier: backend
    project: expense
  ports:
  - protocol: TCP
    port: 3306 # service port
    targetPort: 3306